[http]
host = '0.0.0.0'
port = 8080
hostname = '127.0.0.1:8080'
upload_dir = 'uploads'

[mongodb]
host = 'mongodb'
port = 27017

[cookie]
private_key = 'a super secret key, we should not share it...'
public_key = 'a super public key...'
